/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRentRouteImport } from './routes/_authenticated/rent'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated/files'
import { Route as AuthenticatedElectricityRouteImport } from './routes/_authenticated/electricity'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAgreementsRouteImport } from './routes/_authenticated/agreements'
import { Route as AuthenticatedTenantsIdRouteImport } from './routes/_authenticated/tenants.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRentRoute = AuthenticatedRentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedElectricityRoute =
  AuthenticatedElectricityRouteImport.update({
    id: '/electricity',
    path: '/electricity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgreementsRoute = AuthenticatedAgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsIdRoute = AuthenticatedTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTenantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agreements': typeof AuthenticatedAgreementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/electricity': typeof AuthenticatedElectricityRoute
  '/files': typeof AuthenticatedFilesRoute
  '/rent': typeof AuthenticatedRentRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/tenants/$id': typeof AuthenticatedTenantsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agreements': typeof AuthenticatedAgreementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/electricity': typeof AuthenticatedElectricityRoute
  '/files': typeof AuthenticatedFilesRoute
  '/rent': typeof AuthenticatedRentRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/tenants/$id': typeof AuthenticatedTenantsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agreements': typeof AuthenticatedAgreementsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/electricity': typeof AuthenticatedElectricityRoute
  '/_authenticated/files': typeof AuthenticatedFilesRoute
  '/_authenticated/rent': typeof AuthenticatedRentRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/_authenticated/tenants/$id': typeof AuthenticatedTenantsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agreements'
    | '/dashboard'
    | '/electricity'
    | '/files'
    | '/rent'
    | '/reports'
    | '/settings'
    | '/tenants'
    | '/tenants/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agreements'
    | '/dashboard'
    | '/electricity'
    | '/files'
    | '/rent'
    | '/reports'
    | '/settings'
    | '/tenants'
    | '/tenants/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agreements'
    | '/_authenticated/dashboard'
    | '/_authenticated/electricity'
    | '/_authenticated/files'
    | '/_authenticated/rent'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/tenants'
    | '/_authenticated/tenants/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rent': {
      id: '/_authenticated/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof AuthenticatedRentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/electricity': {
      id: '/_authenticated/electricity'
      path: '/electricity'
      fullPath: '/electricity'
      preLoaderRoute: typeof AuthenticatedElectricityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agreements': {
      id: '/_authenticated/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AuthenticatedAgreementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/$id': {
      id: '/_authenticated/tenants/$id'
      path: '/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof AuthenticatedTenantsIdRouteImport
      parentRoute: typeof AuthenticatedTenantsRoute
    }
  }
}

interface AuthenticatedTenantsRouteChildren {
  AuthenticatedTenantsIdRoute: typeof AuthenticatedTenantsIdRoute
}

const AuthenticatedTenantsRouteChildren: AuthenticatedTenantsRouteChildren = {
  AuthenticatedTenantsIdRoute: AuthenticatedTenantsIdRoute,
}

const AuthenticatedTenantsRouteWithChildren =
  AuthenticatedTenantsRoute._addFileChildren(AuthenticatedTenantsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgreementsRoute: typeof AuthenticatedAgreementsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedElectricityRoute: typeof AuthenticatedElectricityRoute
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRoute
  AuthenticatedRentRoute: typeof AuthenticatedRentRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgreementsRoute: AuthenticatedAgreementsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedElectricityRoute: AuthenticatedElectricityRoute,
  AuthenticatedFilesRoute: AuthenticatedFilesRoute,
  AuthenticatedRentRoute: AuthenticatedRentRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
